server:
  port: 0  # Случайный порт

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: "classpath:/config/"
  config:
    import: "optional:configserver:"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int[1000,9999]}
    prefer-ip-address: false