# Эта конфигурация будет доставлена Aggregator'у через Config Server
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group
      auto-offset-reset: earliest

# Общие настройки логирования
logging:
  level:
    ru.yandex.practicum: INFO
    org.springframework.cloud: INFO