spring.config.import: "optional:configserver:"

spring:
  application:
    name: aggregator
  
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

  kafka:
    bootstrap-servers: localhost:9092  # Значение по умолчанию
    consumer:
      group-id: aggregator-group

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}