spring:
  application:
    name: aggregator
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
        preferred-instance-id: config-server
      fail-fast: false
      uri: ""

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/