# Этот файл БЕЗ spring.config.import - он уже в bootstrap.yaml
# Основные настройки

# Переопределение для CI окружения
---
spring:
  config:
    activate:
      on-profile: ci
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: aggregator-group-ci
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 1

# Логирование для отладки
logging:
  level:
    ru.yandex.practicum: DEBUG
    org.springframework.cloud.config: WARN