# src/main/resources/application.yml
spring:
  application:
    name: analyzer
  
  config:
    import: "optional:configserver:"
  
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: false
      retry:
        max-attempts: 5