spring:
  cloud:
    config:
      uri: http://localhost:8888
      discovery:
        enabled: false
      fail-fast: false
      retry:
        max-attempts: 15
        initial-interval: 2000
        max-interval: 10000
  
  kafka:
    consumer:
      group-id: analyzer-group-ci

# gRPC конфигурация для CI
grpc:
  client:
    hub-router:
      address: static://localhost:59091
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true

# Настройки процессоров
processor:
  initialization:
    timeout: 20000  # 20 секунд в CI
  poll:
    timeout: 1000

logging:
  level:
    ru.yandex.practicum: DEBUG
    ru.yandex.practicum.processor: TRACE
    org.springframework.cloud: WARN
    com.netflix.discovery: WARN