spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/analyzer-smart-home
    username: dbuser
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    consumer:
      group-id: analyzer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true

# gRPC конфигурация
grpc:
  client:
    hub-router:
      address: static://localhost:59091
      negotiation-type: plaintext
      enable-keep-alive: true

  server:
    port: 9094

# Настройки для CI профиля
---
spring:
  config:
    activate:
      on-profile: ci

  kafka:
    consumer:
      group-id: analyzer-group-ci

  cloud:
    config:
      uri: http://localhost:8888
      discovery:
        enabled: false

grpc:
  client:
    hub-router:
      address: static://localhost:59091  # ← ТОЧНО 59091!
      negotiation-type: plaintext